#!/usr/bin/env node
/**
 * License policy check + THIRD_PARTY_LICENSES.md generator.
 *
 *   node tools/scripts/licenses.mjs           check policy and that THIRD_PARTY_LICENSES.md is current
 *   node tools/scripts/licenses.mjs --write   check policy and regenerate THIRD_PARTY_LICENSES.md
 *
 * Policy (see CLAUDE.md → License rule):
 *   runtime   MIT, Apache-2.0, ISC, BSD-2-Clause, BSD-3-Clause, 0BSD; OFL-1.1 for fonts only
 *   dev-only  the runtime list + MPL-2.0 + other permissive public licenses listed below
 *   never     GPL, AGPL, LGPL, SSPL, BUSL, Commons Clause, Elastic, unknown
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const OUTPUT = 'THIRD_PARTY_LICENSES.md';

const RUNTIME_ALLOWED = new Set([
  'MIT',
  'Apache-2.0',
  'ISC',
  'BSD-2-Clause',
  'BSD-3-Clause',
  '0BSD',
]);
const FONT_LICENSES = new Set(['OFL-1.1']);
const FONT_PACKAGE = /^@fontsource(-variable)?\//;

/** Permissive licenses that appear only in build tooling (never shipped to users). */
const DEV_ALLOWED = new Set([
  ...RUNTIME_ALLOWED,
  'MPL-2.0',
  'MIT-0',
  'BlueOak-1.0.0',
  'CC0-1.0',
  'Unlicense',
  'Python-2.0', // argparse (via js-yaml), PSF-style permissive
  'CC-BY-4.0', // caniuse-lite: browser support data, not code
  'WTFPL',
]);

/**
 * Packages whose package.json lacks a license field, verified by reading their LICENSE file.
 * Key: name@version. Re-verify when the version changes.
 */
const VERIFIED_OVERRIDES = {
  'union@0.5.0': 'MIT', // LICENSE file is the MIT text (via @nx/web → http-server, dev only)
};

const FORBIDDEN = /\b(A?GPL|LGPL|SSPL|BUSL|Commons-Clause|Elastic)/i;

function listLicenses(args) {
  const raw = execFileSync('pnpm', ['licenses', 'list', '--json', '-r', ...args], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  });
  const packages = new Map();
  for (const [license, entries] of Object.entries(JSON.parse(raw))) {
    for (const entry of entries) {
      for (const version of entry.versions) {
        const id = `${entry.name}@${version}`;
        packages.set(id, {
          id,
          name: entry.name,
          version,
          license: VERIFIED_OVERRIDES[id] ?? license,
          homepage: entry.homepage ?? '',
          author: typeof entry.author === 'string' ? entry.author : '',
        });
      }
    }
  }
  return packages;
}

/** Evaluates simple SPDX expressions: "A OR B", "(A AND B)". */
function satisfies(expression, allowed) {
  const normalized = expression.replace(/[()]/g, '').trim();
  if (/\bOR\b/.test(normalized)) {
    return normalized.split(/\s+OR\s+/).some((part) => satisfies(part, allowed));
  }
  if (/\bAND\b/.test(normalized)) {
    return normalized.split(/\s+AND\s+/).every((part) => satisfies(part, allowed));
  }
  return allowed.has(normalized);
}

const runtime = listLicenses(['--prod']);
const all = listLicenses([]);
const violations = [];

for (const pkg of runtime.values()) {
  const allowed = FONT_PACKAGE.test(pkg.name)
    ? new Set([...RUNTIME_ALLOWED, ...FONT_LICENSES])
    : RUNTIME_ALLOWED;
  if (FORBIDDEN.test(pkg.license) || !satisfies(pkg.license, allowed)) {
    violations.push(`runtime  ${pkg.id}  ${pkg.license}`);
  }
}
for (const pkg of all.values()) {
  if (runtime.has(pkg.id)) continue;
  if (FORBIDDEN.test(pkg.license) || !satisfies(pkg.license, DEV_ALLOWED)) {
    violations.push(`dev      ${pkg.id}  ${pkg.license}`);
  }
}

if (violations.length > 0) {
  console.error(`License policy violations (${violations.length}):\n  ${violations.join('\n  ')}`);
  console.error(
    '\nRemove the dependency, or verify its license and document it in VERIFIED_OVERRIDES.',
  );
  process.exit(1);
}

const isWorkspacePackage = (name) => name.startsWith('@tassili/');
const rows = [...runtime.values()]
  .filter((pkg) => !isWorkspacePackage(pkg.name))
  .sort((a, b) => a.id.localeCompare(b.id))
  .map((pkg) => `| ${pkg.name} | ${pkg.version} | ${pkg.license} | ${pkg.homepage} |`);

const markdown = `# Third-party licenses

Runtime dependencies of the Tassili packages and template app. Generated by
\`pnpm license:write\`; do not edit by hand. Dev-only tooling is checked by
\`pnpm license:check\` but not listed here because it is not distributed.

| Package | Version | License | Homepage |
| --- | --- | --- | --- |
${rows.join('\n')}
`;

if (process.argv.includes('--write')) {
  writeFileSync(OUTPUT, markdown);
  console.log(`License policy passed. Wrote ${OUTPUT} (${rows.length} runtime packages).`);
} else {
  let current = '';
  try {
    current = readFileSync(OUTPUT, 'utf8');
  } catch {
    // Missing file is reported below.
  }
  if (current !== markdown) {
    console.error(`${OUTPUT} is out of date. Run: pnpm license:write`);
    process.exit(1);
  }
  console.log(
    `License policy passed (${runtime.size} runtime, ${all.size - runtime.size} dev-only packages).`,
  );
}
