export {
  TslAlertDialog,
  TslAlertDialogContent,
  TslAlertDialogDescription,
  TslAlertDialogImports,
  TslAlertDialogPortal,
  TslAlertDialogTitle,
  TslAlertDialogTrigger,
  TslDialog,
  TslDialogClose,
  TslDialogContent,
  TslDialogDescription,
  TslDialogFooter,
  TslDialogHeader,
  TslDialogImports,
  TslDialogPortal,
  TslDialogService,
  TslDialogTitle,
  TslDialogTrigger,
  dialogContentClass,
  dialogOverlayClass,
  type TslDialogOptions,
} from './dialog';
